controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

root:
    path: /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
        path: /docs
        permanent: true

swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui

api_login_check:
    path: /api/login_check